In [1]:
import numpy as np

In [2]:
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [3]:
arr = np.array([0, 1, 2, 3, 4])
type(arr), arr.dtype

(numpy.ndarray, dtype('int64'))

In [4]:
arr = np.arange(10)
arr, type(arr), arr.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray, dtype('int64'))

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10) * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [8]:
print([1., 1.] * 2)

[1.0, 1.0, 1.0, 1.0]


In [9]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [10]:
np.arange(100) % 7

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1])

In [11]:
np.arange(100) % 7 == 0

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False])

In [12]:
np.arange(100) [np.arange(100) % 7 == 0]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [13]:
np.arange(100).reshape([10, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
np.random.randint(1, 100, 3)

array([92, 98,  3], dtype=int32)

In [16]:
np.random.randint(1, 100, (3, 3))

array([[90, 52, 40],
       [86, 73, 20],
       [ 8, 95, 64]], dtype=int32)

In [18]:
np.random.random(3)

array([0.54039769, 0.08058347, 0.84998299])

In [19]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
array = np.random.randint(21, 23, 50)
array

array([22, 22, 21, 22, 22, 22, 22, 21, 22, 22, 22, 21, 22, 22, 21, 22, 22,
       21, 22, 21, 21, 21, 22, 21, 22, 22, 21, 22, 21, 21, 21, 22, 22, 21,
       22, 21, 22, 21, 21, 21, 21, 22, 22, 21, 21, 22, 21, 22, 21, 22],
      dtype=int32)

In [24]:
array [array == 22]

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22], dtype=int32)

In [26]:
array = np.random.randint(2, 10000, 50)
array

array([ 259, 2073, 6285, 2241, 4466, 4761, 7248, 8780, 2689, 1534, 9999,
       1158, 7295, 7156, 8254, 8752, 9174,  832, 8390, 3953, 4725, 4719,
       6340, 2493, 2179, 5472, 8723, 6898, 1465, 5325, 3072, 8231, 7136,
       6923, 9310, 2489, 3459, 9247, 4948, 7169, 6790, 1111,  881, 9312,
       1700, 9053, 8467, 1673,   87, 9463], dtype=int32)

In [27]:
array.max(), array.argmax()

(np.int32(9999), np.int64(10))